"use client";

import { useMemo, useState } from "react";
import { Check, Download } from "lucide-react";

function buildChecklist(intl: boolean, flying: boolean, driving: boolean) {
  return [
    { when: "6–8 weeks before", items: [
      intl ? "Check passport is valid 6+ months beyond travel" : "",
      intl ? "Apply for visa / entry permit if required" : "",
      intl ? "Check recommended vaccinations & health advice" : "",
      "Buy travel insurance", "Confirm all bookings (stay, transfers, tours)",
      "Note any special requests (diet, access, celebrations)",
    ].filter(Boolean) },
    { when: "2–3 weeks before", items: [
      "Arrange airport transfers / parking", "Order foreign currency", flying ? "Choose seats / add baggage" : "",
      driving ? "Check driving licence & International Driving Permit" : "",
      "Set up any medications / repeat prescriptions", "Tell your bank you're travelling",
    ].filter(Boolean) },
    { when: "1 week before", items: [
      "Print / download all confirmations & vouchers", "Save offline maps & itinerary",
      "Share itinerary with family / friend", "Check weather & finalise packing",
      "Charge devices & pack adapters / power bank",
    ] },
    { when: "Day before", items: [
      flying ? "Online check-in & download boarding passes" : "", "Pack essentials in carry-on (meds, docs, valuables)",
      "Confirm pickup / transfer time", "Set out-of-office & auto-replies", "Charge phone, watch & power bank",
    ].filter(Boolean) },
    { when: "Departure day", items: [
      "Passport, ID, cards & currency on you", "Home secured (lights, taps, heating, bins)",
      "Bins out / plants & pets arranged", "Leave with time to spare", "Bon voyage — safe travels!",
    ] },
  ];
}

export default function ChecklistGenerator() {
  const [intl, setIntl] = useState(true);
  const [flying, setFlying] = useState(true);
  const [driving, setDriving] = useState(false);
  const [done, setDone] = useState<Set<string>>(new Set());
  const [busy, setBusy] = useState(false);

  const groups = useMemo(() => buildChecklist(intl, flying, driving), [intl, flying, driving]);
  const total = groups.reduce((s, g) => s + g.items.length, 0);
  const checked = groups.reduce((s, g) => s + g.items.filter(i => done.has(`${g.when}:${i}`)).length, 0);
  const toggle = (k: string) => setDone(p => { const n = new Set(p); n.has(k) ? n.delete(k) : n.add(k); return n; });

  // Real PDF — window.print() silently no-ops in many mobile / in-app browsers.
  const downloadPdf = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const W = 210, M = 16;
      doc.setFillColor(33, 29, 24); doc.rect(0, 0, W, 26, "F");
      doc.setTextColor(244, 240, 233); doc.setFont("times", "normal"); doc.setFontSize(20);
      doc.text("Voyages & Co.", M, 14);
      doc.setTextColor(201, 174, 119); doc.setFont("helvetica", "normal"); doc.setFontSize(8);
      doc.text("TRAVEL CHECKLIST", M, 21, { charSpace: 1.2 });

      let y = 38;
      doc.setTextColor(140, 140, 140); doc.setFontSize(9);
      doc.text([intl ? "International" : "Domestic", flying ? "Flying" : "", driving ? "Driving abroad" : ""].filter(Boolean).join("  ·  "), M, y);
      y += 9;

      for (const g of groups) {
        if (y > 272) { doc.addPage(); y = 20; }
        doc.setTextColor(201, 174, 119); doc.setFont("helvetica", "bold"); doc.setFontSize(9);
        doc.text(g.when.toUpperCase(), M, y, { charSpace: 1 });
        y += 6;
        doc.setFont("helvetica", "normal"); doc.setFontSize(10.5); doc.setTextColor(33, 29, 24);
        for (const item of g.items) {
          if (y > 285) { doc.addPage(); y = 20; }
          doc.setDrawColor(150, 150, 150); doc.rect(M, y - 3.1, 3.4, 3.4);
          const lines = doc.splitTextToSize(item, W - M * 2 - 8);
          doc.text(lines, M + 6, y);
          y += Math.max(1, lines.length) * 5 + 1.4;
        }
        y += 4.5;
      }

      doc.setTextColor(150, 150, 150); doc.setFontSize(8);
      doc.text("Generated by Voyages & Co. · voyagesco.com", M, 290);
      doc.save("travel-checklist.pdf");
    } finally {
      setBusy(false);
    }
  };

  const Opt = ({ on, set, label }: { on: boolean; set: (v: boolean) => void; label: string }) => (
    <label className="flex items-center gap-2.5 text-sm text-ink-muted cursor-pointer">
      <input type="checkbox" checked={on} onChange={e => set(e.target.checked)} /> {label}
    </label>
  );

  return (
    <div>
      <div className="flex flex-wrap gap-x-6 gap-y-2 mb-6 print:hidden">
        <Opt on={intl} set={setIntl} label="International trip" />
        <Opt on={flying} set={setFlying} label="Flying" />
        <Opt on={driving} set={setDriving} label="Driving abroad" />
        <button onClick={downloadPdf} disabled={busy} className="ml-auto inline-flex items-center gap-1.5 text-xs tracking-[0.1em] uppercase text-ink-muted hover:text-ink disabled:opacity-50 transition-colors">
          <Download size={14} /> {busy ? "Preparing…" : "Download"}
        </button>
      </div>

      <p className="text-sm text-ink-muted mb-5">{checked}/{total} done</p>

      <div className="relative space-y-8">
        {groups.map(g => (
          <div key={g.when} className="relative pl-6 border-l-2 border-line">
            <span className="absolute -left-[7px] top-1 w-3 h-3 rounded-full bg-gold" />
            <p className="text-[11px] tracking-[0.18em] uppercase text-gold mb-2">{g.when}</p>
            <ul className="space-y-1">
              {g.items.map(item => {
                const k = `${g.when}:${item}`;
                const on = done.has(k);
                return (
                  <li key={k}>
                    <button onClick={() => toggle(k)} className="flex items-center gap-3 w-full text-left py-1 group">
                      <span className={`w-4 h-4 border flex items-center justify-center shrink-0 ${on ? "bg-gold border-gold" : "border-line-strong group-hover:border-ink"}`}>
                        {on && <Check size={12} className="text-page" />}
                      </span>
                      <span className={`text-sm ${on ? "text-ink-faint line-through" : "text-ink"}`}>{item}</span>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}
