import type { Airline } from "./types";

export const AIRLINES: Airline[] = [
  // ── India ────────────────────────────────────────────────────────────────────
  { code: "AI", name: "Air India", country: "India" },
  { code: "6E", name: "IndiGo", country: "India" },
  { code: "UK", name: "Vistara", country: "India" },
  { code: "SG", name: "SpiceJet", country: "India" },
  { code: "QP", name: "Akasa Air", country: "India" },
  { code: "G8", name: "Go First", country: "India" },
  { code: "I5", name: "AirAsia India", country: "India" },
  { code: "9I", name: "Alliance Air", country: "India" },
  { code: "IX", name: "Air India Express", country: "India" },
  { code: "IC", name: "Fly91", country: "India" },
  { code: "S5", name: "Star Air", country: "India" },
  { code: "ZS", name: "Shankh Air", country: "India" },
  // ── Middle East ──────────────────────────────────────────────────────────────
  { code: "EK", name: "Emirates", country: "UAE" },
  { code: "EY", name: "Etihad Airways", country: "UAE" },
  { code: "FZ", name: "flydubai", country: "UAE" },
  { code: "G9", name: "Air Arabia", country: "UAE" },
  { code: "QR", name: "Qatar Airways", country: "Qatar" },
  { code: "SV", name: "Saudia", country: "Saudi Arabia" },
  { code: "F3", name: "flynas", country: "Saudi Arabia" },
  { code: "GF", name: "Gulf Air", country: "Bahrain" },
  { code: "WY", name: "Oman Air", country: "Oman" },
  { code: "KU", name: "Kuwait Airways", country: "Kuwait" },
  { code: "J9", name: "Jazeera Airways", country: "Kuwait" },
  { code: "RJ", name: "Royal Jordanian", country: "Jordan" },
  { code: "LY", name: "El Al", country: "Israel" },
  { code: "ME", name: "Middle East Airlines", country: "Lebanon" },
  { code: "IA", name: "Iraqi Airways", country: "Iraq" },
  { code: "IR", name: "Iran Air", country: "Iran" },
  // ── Southeast & South Asia ───────────────────────────────────────────────────
  { code: "SQ", name: "Singapore Airlines", country: "Singapore" },
  { code: "TR", name: "Scoot", country: "Singapore" },
  { code: "TG", name: "Thai Airways", country: "Thailand" },
  { code: "FD", name: "Thai AirAsia", country: "Thailand" },
  { code: "PG", name: "Bangkok Airways", country: "Thailand" },
  { code: "MH", name: "Malaysia Airlines", country: "Malaysia" },
  { code: "AK", name: "AirAsia", country: "Malaysia" },
  { code: "D7", name: "AirAsia X", country: "Malaysia" },
  { code: "GA", name: "Garuda Indonesia", country: "Indonesia" },
  { code: "ID", name: "Batik Air", country: "Indonesia" },
  { code: "JT", name: "Lion Air", country: "Indonesia" },
  { code: "QZ", name: "Indonesia AirAsia", country: "Indonesia" },
  { code: "PR", name: "Philippine Airlines", country: "Philippines" },
  { code: "5J", name: "Cebu Pacific", country: "Philippines" },
  { code: "VN", name: "Vietnam Airlines", country: "Vietnam" },
  { code: "VJ", name: "VietJet Air", country: "Vietnam" },
  { code: "QH", name: "Bamboo Airways", country: "Vietnam" },
  { code: "UL", name: "SriLankan Airlines", country: "Sri Lanka" },
  { code: "Q2", name: "Maldivian", country: "Maldives" },
  { code: "RA", name: "Nepal Airlines", country: "Nepal" },
  { code: "KB", name: "Drukair", country: "Bhutan" },
  { code: "B3", name: "Bhutan Airlines", country: "Bhutan" },
  { code: "PK", name: "Pakistan International Airlines", country: "Pakistan" },
  { code: "BG", name: "Biman Bangladesh Airlines", country: "Bangladesh" },
  { code: "K6", name: "Cambodia Angkor Air", country: "Cambodia" },
  { code: "QV", name: "Lao Airlines", country: "Laos" },
  // ── East Asia & Pacific ──────────────────────────────────────────────────────
  { code: "CX", name: "Cathay Pacific", country: "Hong Kong" },
  { code: "HX", name: "Hong Kong Airlines", country: "Hong Kong" },
  { code: "CI", name: "China Airlines", country: "Taiwan" },
  { code: "BR", name: "EVA Air", country: "Taiwan" },
  { code: "CA", name: "Air China", country: "China" },
  { code: "MU", name: "China Eastern Airlines", country: "China" },
  { code: "CZ", name: "China Southern Airlines", country: "China" },
  { code: "HU", name: "Hainan Airlines", country: "China" },
  { code: "FM", name: "Shanghai Airlines", country: "China" },
  { code: "MF", name: "Xiamen Airlines", country: "China" },
  { code: "ZH", name: "Shenzhen Airlines", country: "China" },
  { code: "KE", name: "Korean Air", country: "South Korea" },
  { code: "OZ", name: "Asiana Airlines", country: "South Korea" },
  { code: "TW", name: "T'way Air", country: "South Korea" },
  { code: "NH", name: "All Nippon Airways", country: "Japan" },
  { code: "JL", name: "Japan Airlines", country: "Japan" },
  { code: "MM", name: "Peach Aviation", country: "Japan" },
  { code: "GK", name: "Jetstar Japan", country: "Japan" },
  { code: "QF", name: "Qantas", country: "Australia" },
  { code: "VA", name: "Virgin Australia", country: "Australia" },
  { code: "JQ", name: "Jetstar Airways", country: "Australia" },
  { code: "NZ", name: "Air New Zealand", country: "New Zealand" },
  { code: "FJ", name: "Fiji Airways", country: "Fiji" },
  // ── Europe ───────────────────────────────────────────────────────────────────
  { code: "BA", name: "British Airways", country: "UK" },
  { code: "VS", name: "Virgin Atlantic", country: "UK" },
  { code: "U2", name: "easyJet", country: "UK" },
  { code: "AF", name: "Air France", country: "France" },
  { code: "TX", name: "Air Caraïbes", country: "France" },
  { code: "LH", name: "Lufthansa", country: "Germany" },
  { code: "EW", name: "Eurowings", country: "Germany" },
  { code: "DE", name: "Condor", country: "Germany" },
  { code: "KL", name: "KLM Royal Dutch Airlines", country: "Netherlands" },
  { code: "LX", name: "Swiss International Air Lines", country: "Switzerland" },
  { code: "OS", name: "Austrian Airlines", country: "Austria" },
  { code: "IB", name: "Iberia", country: "Spain" },
  { code: "VY", name: "Vueling", country: "Spain" },
  { code: "AZ", name: "ITA Airways", country: "Italy" },
  { code: "A3", name: "Aegean Airlines", country: "Greece" },
  { code: "TK", name: "Turkish Airlines", country: "Turkey" },
  { code: "PC", name: "Pegasus Airlines", country: "Turkey" },
  { code: "SK", name: "Scandinavian Airlines (SAS)", country: "Sweden" },
  { code: "DY", name: "Norwegian Air Shuttle", country: "Norway" },
  { code: "AY", name: "Finnair", country: "Finland" },
  { code: "FI", name: "Icelandair", country: "Iceland" },
  { code: "SN", name: "Brussels Airlines", country: "Belgium" },
  { code: "TP", name: "TAP Air Portugal", country: "Portugal" },
  { code: "EI", name: "Aer Lingus", country: "Ireland" },
  { code: "FR", name: "Ryanair", country: "Ireland" },
  { code: "LO", name: "LOT Polish Airlines", country: "Poland" },
  { code: "OK", name: "Czech Airlines", country: "Czech Republic" },
  { code: "W6", name: "Wizz Air", country: "Hungary" },
  { code: "SU", name: "Aeroflot", country: "Russia" },
  { code: "S7", name: "S7 Airlines", country: "Russia" },
  { code: "RO", name: "TAROM", country: "Romania" },
  { code: "FB", name: "Bulgaria Air", country: "Bulgaria" },
  { code: "JU", name: "Air Serbia", country: "Serbia" },
  { code: "OU", name: "Croatia Airlines", country: "Croatia" },
  { code: "BT", name: "airBaltic", country: "Latvia" },
  // ── North America ────────────────────────────────────────────────────────────
  { code: "AA", name: "American Airlines", country: "USA" },
  { code: "DL", name: "Delta Air Lines", country: "USA" },
  { code: "UA", name: "United Airlines", country: "USA" },
  { code: "WN", name: "Southwest Airlines", country: "USA" },
  { code: "B6", name: "JetBlue Airways", country: "USA" },
  { code: "AS", name: "Alaska Airlines", country: "USA" },
  { code: "NK", name: "Spirit Airlines", country: "USA" },
  { code: "F9", name: "Frontier Airlines", country: "USA" },
  { code: "G4", name: "Allegiant Air", country: "USA" },
  { code: "HA", name: "Hawaiian Airlines", country: "USA" },
  { code: "SY", name: "Sun Country Airlines", country: "USA" },
  { code: "AC", name: "Air Canada", country: "Canada" },
  { code: "WS", name: "WestJet", country: "Canada" },
  { code: "PD", name: "Porter Airlines", country: "Canada" },
  { code: "AM", name: "Aeroméxico", country: "Mexico" },
  { code: "Y4", name: "Volaris", country: "Mexico" },
  { code: "VB", name: "VivaAerobus", country: "Mexico" },
  { code: "CM", name: "Copa Airlines", country: "Panama" },
  { code: "TA", name: "Avianca", country: "Colombia" },
  // ── South America ────────────────────────────────────────────────────────────
  { code: "LA", name: "LATAM Airlines", country: "Chile" },
  { code: "G3", name: "Gol Linhas Aéreas", country: "Brazil" },
  { code: "AD", name: "Azul Brazilian Airlines", country: "Brazil" },
  { code: "AR", name: "Aerolíneas Argentinas", country: "Argentina" },
  { code: "H2", name: "Sky Airline", country: "Chile" },
  { code: "P9", name: "Peruvian Airlines", country: "Peru" },
  { code: "5U", name: "Bolivia de Aviación (BoA)", country: "Bolivia" },
  // ── Africa ───────────────────────────────────────────────────────────────────
  { code: "ET", name: "Ethiopian Airlines", country: "Ethiopia" },
  { code: "KQ", name: "Kenya Airways", country: "Kenya" },
  { code: "SA", name: "South African Airways", country: "South Africa" },
  { code: "MN", name: "Airlink", country: "South Africa" },
  { code: "MS", name: "EgyptAir", country: "Egypt" },
  { code: "AT", name: "Royal Air Maroc", country: "Morocco" },
  { code: "AH", name: "Air Algérie", country: "Algeria" },
  { code: "TU", name: "Tunisair", country: "Tunisia" },
  { code: "WB", name: "RwandAir", country: "Rwanda" },
  { code: "MK", name: "Air Mauritius", country: "Mauritius" },
  { code: "HM", name: "Air Seychelles", country: "Seychelles" },
  { code: "W3", name: "Arik Air", country: "Nigeria" },
  { code: "P4", name: "Air Peace", country: "Nigeria" },
  { code: "KP", name: "ASKY Airlines", country: "Togo" },
  { code: "TC", name: "Air Tanzania", country: "Tanzania" },
];
