// Country → ISO-3166 alpha-2 code + local currency, for destination features
// (public-holiday lookups and the currency cheat-sheet). Covers the countries
// used across the catalogue; unknown names resolve to null and the cards hide.

export type CountryMeta = { iso2: string; ccy: string; ccyName: string; symbol: string };

const DATA: Record<string, CountryMeta> = {
  India: { iso2: "IN", ccy: "INR", ccyName: "Indian Rupee", symbol: "₹" },
  Maldives: { iso2: "MV", ccy: "MVR", ccyName: "Maldivian Rufiyaa", symbol: "Rf" },
  "Sri Lanka": { iso2: "LK", ccy: "LKR", ccyName: "Sri Lankan Rupee", symbol: "Rs" },
  Nepal: { iso2: "NP", ccy: "NPR", ccyName: "Nepalese Rupee", symbol: "रू" },
  Bhutan: { iso2: "BT", ccy: "BTN", ccyName: "Bhutanese Ngultrum", symbol: "Nu." },
  Bangladesh: { iso2: "BD", ccy: "BDT", ccyName: "Bangladeshi Taka", symbol: "৳" },
  Pakistan: { iso2: "PK", ccy: "PKR", ccyName: "Pakistani Rupee", symbol: "₨" },
  Thailand: { iso2: "TH", ccy: "THB", ccyName: "Thai Baht", symbol: "฿" },
  Indonesia: { iso2: "ID", ccy: "IDR", ccyName: "Indonesian Rupiah", symbol: "Rp" },
  Vietnam: { iso2: "VN", ccy: "VND", ccyName: "Vietnamese Dong", symbol: "₫" },
  Cambodia: { iso2: "KH", ccy: "KHR", ccyName: "Cambodian Riel", symbol: "៛" },
  Laos: { iso2: "LA", ccy: "LAK", ccyName: "Lao Kip", symbol: "₭" },
  Myanmar: { iso2: "MM", ccy: "MMK", ccyName: "Myanmar Kyat", symbol: "K" },
  Malaysia: { iso2: "MY", ccy: "MYR", ccyName: "Malaysian Ringgit", symbol: "RM" },
  Singapore: { iso2: "SG", ccy: "SGD", ccyName: "Singapore Dollar", symbol: "S$" },
  Philippines: { iso2: "PH", ccy: "PHP", ccyName: "Philippine Peso", symbol: "₱" },
  Brunei: { iso2: "BN", ccy: "BND", ccyName: "Brunei Dollar", symbol: "B$" },
  Japan: { iso2: "JP", ccy: "JPY", ccyName: "Japanese Yen", symbol: "¥" },
  China: { iso2: "CN", ccy: "CNY", ccyName: "Chinese Yuan", symbol: "¥" },
  "Hong Kong": { iso2: "HK", ccy: "HKD", ccyName: "Hong Kong Dollar", symbol: "HK$" },
  Taiwan: { iso2: "TW", ccy: "TWD", ccyName: "New Taiwan Dollar", symbol: "NT$" },
  "South Korea": { iso2: "KR", ccy: "KRW", ccyName: "South Korean Won", symbol: "₩" },
  UAE: { iso2: "AE", ccy: "AED", ccyName: "UAE Dirham", symbol: "د.إ" },
  "United Arab Emirates": { iso2: "AE", ccy: "AED", ccyName: "UAE Dirham", symbol: "د.إ" },
  Oman: { iso2: "OM", ccy: "OMR", ccyName: "Omani Rial", symbol: "ر.ع." },
  Qatar: { iso2: "QA", ccy: "QAR", ccyName: "Qatari Riyal", symbol: "ر.ق" },
  Bahrain: { iso2: "BH", ccy: "BHD", ccyName: "Bahraini Dinar", symbol: ".د.ب" },
  Kuwait: { iso2: "KW", ccy: "KWD", ccyName: "Kuwaiti Dinar", symbol: "د.ك" },
  "Saudi Arabia": { iso2: "SA", ccy: "SAR", ccyName: "Saudi Riyal", symbol: "﷼" },
  Jordan: { iso2: "JO", ccy: "JOD", ccyName: "Jordanian Dinar", symbol: "د.ا" },
  Israel: { iso2: "IL", ccy: "ILS", ccyName: "Israeli Shekel", symbol: "₪" },
  Lebanon: { iso2: "LB", ccy: "LBP", ccyName: "Lebanese Pound", symbol: "ل.ل" },
  Iran: { iso2: "IR", ccy: "IRR", ccyName: "Iranian Rial", symbol: "﷼" },
  Iraq: { iso2: "IQ", ccy: "IQD", ccyName: "Iraqi Dinar", symbol: "ع.د" },
  Egypt: { iso2: "EG", ccy: "EGP", ccyName: "Egyptian Pound", symbol: "ج.م" },
  Morocco: { iso2: "MA", ccy: "MAD", ccyName: "Moroccan Dirham", symbol: "د.م." },
  Tunisia: { iso2: "TN", ccy: "TND", ccyName: "Tunisian Dinar", symbol: "د.ت" },
  Algeria: { iso2: "DZ", ccy: "DZD", ccyName: "Algerian Dinar", symbol: "دج" },
  Kenya: { iso2: "KE", ccy: "KES", ccyName: "Kenyan Shilling", symbol: "KSh" },
  Tanzania: { iso2: "TZ", ccy: "TZS", ccyName: "Tanzanian Shilling", symbol: "TSh" },
  Uganda: { iso2: "UG", ccy: "UGX", ccyName: "Ugandan Shilling", symbol: "USh" },
  Ethiopia: { iso2: "ET", ccy: "ETB", ccyName: "Ethiopian Birr", symbol: "Br" },
  Ghana: { iso2: "GH", ccy: "GHS", ccyName: "Ghanaian Cedi", symbol: "₵" },
  Nigeria: { iso2: "NG", ccy: "NGN", ccyName: "Nigerian Naira", symbol: "₦" },
  Senegal: { iso2: "SN", ccy: "XOF", ccyName: "West African CFA Franc", symbol: "CFA" },
  "South Africa": { iso2: "ZA", ccy: "ZAR", ccyName: "South African Rand", symbol: "R" },
  Zambia: { iso2: "ZM", ccy: "ZMW", ccyName: "Zambian Kwacha", symbol: "ZK" },
  Mauritius: { iso2: "MU", ccy: "MUR", ccyName: "Mauritian Rupee", symbol: "₨" },
  Seychelles: { iso2: "SC", ccy: "SCR", ccyName: "Seychellois Rupee", symbol: "₨" },
  Turkey: { iso2: "TR", ccy: "TRY", ccyName: "Turkish Lira", symbol: "₺" },
  Italy: { iso2: "IT", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  France: { iso2: "FR", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Spain: { iso2: "ES", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Portugal: { iso2: "PT", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Greece: { iso2: "GR", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Germany: { iso2: "DE", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Netherlands: { iso2: "NL", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Belgium: { iso2: "BE", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Austria: { iso2: "AT", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Ireland: { iso2: "IE", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Finland: { iso2: "FI", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Estonia: { iso2: "EE", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Latvia: { iso2: "LV", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Lithuania: { iso2: "LT", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Slovakia: { iso2: "SK", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Slovenia: { iso2: "SI", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Croatia: { iso2: "HR", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  Montenegro: { iso2: "ME", ccy: "EUR", ccyName: "Euro", symbol: "€" },
  UK: { iso2: "GB", ccy: "GBP", ccyName: "British Pound", symbol: "£" },
  "United Kingdom": { iso2: "GB", ccy: "GBP", ccyName: "British Pound", symbol: "£" },
  Switzerland: { iso2: "CH", ccy: "CHF", ccyName: "Swiss Franc", symbol: "CHF" },
  Norway: { iso2: "NO", ccy: "NOK", ccyName: "Norwegian Krone", symbol: "kr" },
  Sweden: { iso2: "SE", ccy: "SEK", ccyName: "Swedish Krona", symbol: "kr" },
  Denmark: { iso2: "DK", ccy: "DKK", ccyName: "Danish Krone", symbol: "kr" },
  Iceland: { iso2: "IS", ccy: "ISK", ccyName: "Icelandic Króna", symbol: "kr" },
  Poland: { iso2: "PL", ccy: "PLN", ccyName: "Polish Złoty", symbol: "zł" },
  "Czech Republic": { iso2: "CZ", ccy: "CZK", ccyName: "Czech Koruna", symbol: "Kč" },
  Hungary: { iso2: "HU", ccy: "HUF", ccyName: "Hungarian Forint", symbol: "Ft" },
  Romania: { iso2: "RO", ccy: "RON", ccyName: "Romanian Leu", symbol: "lei" },
  Bulgaria: { iso2: "BG", ccy: "BGN", ccyName: "Bulgarian Lev", symbol: "лв" },
  Serbia: { iso2: "RS", ccy: "RSD", ccyName: "Serbian Dinar", symbol: "дин" },
  Albania: { iso2: "AL", ccy: "ALL", ccyName: "Albanian Lek", symbol: "L" },
  Bosnia: { iso2: "BA", ccy: "BAM", ccyName: "Bosnia Convertible Mark", symbol: "KM" },
  "North Macedonia": { iso2: "MK", ccy: "MKD", ccyName: "Macedonian Denar", symbol: "ден" },
  Russia: { iso2: "RU", ccy: "RUB", ccyName: "Russian Ruble", symbol: "₽" },
  USA: { iso2: "US", ccy: "USD", ccyName: "US Dollar", symbol: "$" },
  "United States": { iso2: "US", ccy: "USD", ccyName: "US Dollar", symbol: "$" },
  Canada: { iso2: "CA", ccy: "CAD", ccyName: "Canadian Dollar", symbol: "C$" },
  Mexico: { iso2: "MX", ccy: "MXN", ccyName: "Mexican Peso", symbol: "Mex$" },
  "Costa Rica": { iso2: "CR", ccy: "CRC", ccyName: "Costa Rican Colón", symbol: "₡" },
  Panama: { iso2: "PA", ccy: "USD", ccyName: "US Dollar", symbol: "$" },
  Guatemala: { iso2: "GT", ccy: "GTQ", ccyName: "Guatemalan Quetzal", symbol: "Q" },
  Belize: { iso2: "BZ", ccy: "BZD", ccyName: "Belize Dollar", symbol: "BZ$" },
  Honduras: { iso2: "HN", ccy: "HNL", ccyName: "Honduran Lempira", symbol: "L" },
  Nicaragua: { iso2: "NI", ccy: "NIO", ccyName: "Nicaraguan Córdoba", symbol: "C$" },
  "El Salvador": { iso2: "SV", ccy: "USD", ccyName: "US Dollar", symbol: "$" },
  Cuba: { iso2: "CU", ccy: "CUP", ccyName: "Cuban Peso", symbol: "$" },
  Jamaica: { iso2: "JM", ccy: "JMD", ccyName: "Jamaican Dollar", symbol: "J$" },
  Bahamas: { iso2: "BS", ccy: "BSD", ccyName: "Bahamian Dollar", symbol: "B$" },
  Barbados: { iso2: "BB", ccy: "BBD", ccyName: "Barbadian Dollar", symbol: "Bds$" },
  "Dominican Republic": { iso2: "DO", ccy: "DOP", ccyName: "Dominican Peso", symbol: "RD$" },
  Aruba: { iso2: "AW", ccy: "AWG", ccyName: "Aruban Florin", symbol: "ƒ" },
  Brazil: { iso2: "BR", ccy: "BRL", ccyName: "Brazilian Real", symbol: "R$" },
  Argentina: { iso2: "AR", ccy: "ARS", ccyName: "Argentine Peso", symbol: "$" },
  Chile: { iso2: "CL", ccy: "CLP", ccyName: "Chilean Peso", symbol: "$" },
  Peru: { iso2: "PE", ccy: "PEN", ccyName: "Peruvian Sol", symbol: "S/" },
  Colombia: { iso2: "CO", ccy: "COP", ccyName: "Colombian Peso", symbol: "$" },
  Ecuador: { iso2: "EC", ccy: "USD", ccyName: "US Dollar", symbol: "$" },
  Bolivia: { iso2: "BO", ccy: "BOB", ccyName: "Bolivian Boliviano", symbol: "Bs" },
  Paraguay: { iso2: "PY", ccy: "PYG", ccyName: "Paraguayan Guaraní", symbol: "₲" },
  Uruguay: { iso2: "UY", ccy: "UYU", ccyName: "Uruguayan Peso", symbol: "$U" },
  Australia: { iso2: "AU", ccy: "AUD", ccyName: "Australian Dollar", symbol: "A$" },
  "New Zealand": { iso2: "NZ", ccy: "NZD", ccyName: "New Zealand Dollar", symbol: "NZ$" },
  Fiji: { iso2: "FJ", ccy: "FJD", ccyName: "Fijian Dollar", symbol: "FJ$" },
  "French Polynesia": { iso2: "PF", ccy: "XPF", ccyName: "CFP Franc", symbol: "₣" },
  Samoa: { iso2: "WS", ccy: "WST", ccyName: "Samoan Tālā", symbol: "T" },
  Tonga: { iso2: "TO", ccy: "TOP", ccyName: "Tongan Paʻanga", symbol: "T$" },
};

const ALIAS: Record<string, string> = {
  "United Arab Emirates": "UAE",
  "United Kingdom": "UK",
  "United States": "USA",
};

export function getCountryMeta(country?: string | null): CountryMeta | null {
  if (!country) return null;
  return DATA[country] ?? DATA[ALIAS[country] ?? ""] ?? null;
}
